SELECT ATC.OWNER
      ,ATC.TABLE_NAME
      ,U_TAB.NUM_ROWS
      ,T_COM.COMMENTS
      ,ATC.COLUMN_NAME
  FROM ALL_TAB_COLUMNS  ATC
      ,ALL_TAB_COMMENTS T_COM
      ,ALL_TABLES       U_TAB
 WHERE ATC.TABLE_NAME = T_COM.TABLE_NAME(+)
   AND ATC.TABLE_NAME = U_TAB.TABLE_NAME(+)
   AND UPPER(ATC.COLUMN_NAME) LIKE UPPER('%AGENT%')
   AND UPPER(ATC.OWNER) = UPPER('PARUS')
 ORDER BY 1
         ,2
