CREATE OR REPLACE PROCEDURE P_RUS_TEST1(NCOMPANY IN NUMBER) AS
	/* константы листа */
	SHEET_NAME   CONSTANT PKG_STD.TSTRING := 'Лист1'; -- Имя листа-шаблона
	CELL_COMPANY CONSTANT PKG_STD.TSTRING := 'organiz';
	/* переменные */
	SCOMPANY VARCHAR2(100);
BEGIN
	SCOMPANY := GET_COMPANY_FULLNAME(0, NCOMPANY);
	/* пролог */
	PRSG_EXCEL.PREPARE;
	/* установка текущего рабочего листа */
	PRSG_EXCEL.SHEET_SELECT(SHEET_NAME);
	/* описание */
	PRSG_EXCEL.CELL_DESCRIBE(CELL_COMPANY);
	/* запись значений */
	PRSG_EXCEL.CELL_VALUE_WRITE(CELL_COMPANY, SCOMPANY);

END;
