CREATE OR REPLACE PROCEDURE P_RUS_TEST4(P_NAME IN VARCHAR2) AS
  SHEET_NAME   CONSTANT PKG_STD.TSTRING := 'Лист1';
  C_HEADER     CONSTANT PKG_STD.TSTRING := 'HEADER';
  C_ROW        CONSTANT PKG_STD.TSTRING := 'ROW';
  C_RN         CONSTANT PKG_STD.TSTRING := 'RN';
  C_NAME       CONSTANT PKG_STD.TSTRING := 'NAME';
  C_FULLNAME   CONSTANT PKG_STD.TSTRING := 'FULLNAME';

  ILINE_INDEX  INTEGER;
  
BEGIN
	IF P_NAME IS NULL THEN
	  P_EXCEPTION(0, 'P_NAME IS NULL');
	END IF;
	
  /* пролог */
  PRSG_EXCEL.PREPARE;
  
  /* установка текущего рабочего листа */
  PRSG_EXCEL.SHEET_SELECT(SHEET_NAME);
  
  /* описание */
  PRSG_EXCEL.LINE_DESCRIBE(C_HEADER);
  PRSG_EXCEL.LINE_DESCRIBE(C_ROW);
  
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_RN);
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_NAME);
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_FULLNAME);

  /* запись значений */
  FOR REC IN (
    SELECT C.RN
          ,C.NAME
          ,C.FULLNAME
      FROM COMPANIES C
		 WHERE UPPER(C.NAME) LIKE UPPER('%'||P_NAME||'%')) LOOP
  
    /* добавление строки контрагента */
    ILINE_INDEX := PRSG_EXCEL.LINE_CONTINUE(C_ROW);
  
    /* запись значений */
    PRSG_EXCEL.CELL_VALUE_WRITE(C_RN, 0, ILINE_INDEX, REC.RN);
    PRSG_EXCEL.CELL_VALUE_WRITE(C_NAME, 0, ILINE_INDEX, REC.NAME);
    PRSG_EXCEL.CELL_VALUE_WRITE(C_FULLNAME, 0, ILINE_INDEX, REC.FULLNAME);
  
  END LOOP;

  PRSG_EXCEL.LINE_DELETE(C_ROW);

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		P_EXCEPTION(0, 'NO DATA FOUND');
	WHEN OTHERS THEN
		P_EXCEPTION(0, 'EXCEPTION: '||SQLERRM);
END;


















