CREATE OR REPLACE PROCEDURE P_RUS_TEST6(P_NAME IN VARCHAR2) 
AS
  SHEET_NAME   CONSTANT PKG_STD.TSTRING := 'Лист1';
  C_HEADER     CONSTANT PKG_STD.TSTRING := 'HEADER';
  C_ROW        CONSTANT PKG_STD.TSTRING := 'ROW';
  C_RN         CONSTANT PKG_STD.TSTRING := 'RN';
  C_NAME       CONSTANT PKG_STD.TSTRING := 'NAME';
  C_FULLNAME   CONSTANT PKG_STD.TSTRING := 'FULLNAME';
	C_PARAM      CONSTANT PKG_STD.TSTRING := 'PRMS';

  ILINE_INDEX  INTEGER;
	
	V_PNAME      VARCHAR2(1000) := P_NAME;
	V_CUR        SYS_REFCURSOR;
	V_SQL        VARCHAR2(4000);
	
	V_RN         COMPANIES.RN%TYPE;
	V_NAME       COMPANIES.NAME%TYPE;
	V_FULLNAME   COMPANIES.FULLNAME%TYPE;
  
BEGIN
  V_SQL := '
	  SELECT C.RN
          ,C.NAME
          ,C.FULLNAME
      FROM COMPANIES C
			/*FILTER*/
	';
	
	IF TRIM(V_PNAME) IS NOT NULL THEN
		IF REGEXP_COUNT(V_PNAME, ';') > 0 THEN
			V_PNAME := REPLACE(V_PNAME, ';', q'[',']');
			V_SQL := REPLACE(V_SQL, '/*FILTER*/', q'[WHERE C.NAME IN (']' || V_PNAME || q'[')]');
	  ELSE
		  V_SQL := REPLACE(V_SQL, '/*FILTER*/', q'[WHERE C.NAME = ']' || V_PNAME || q'[']' );
		END IF;
	END IF;
  
  /* пролог */
  PRSG_EXCEL.PREPARE;
  
  /* установка текущего рабочего листа */
  PRSG_EXCEL.SHEET_SELECT(SHEET_NAME);
  
  /* описание */
  PRSG_EXCEL.LINE_DESCRIBE(C_HEADER);
  PRSG_EXCEL.LINE_DESCRIBE(C_ROW);
  
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_RN);
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_NAME);
  PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_FULLNAME);
	PRSG_EXCEL.LINE_CELL_DESCRIBE(C_ROW, C_PARAM);

  /* запись значений */
  OPEN V_CUR FOR V_SQL; 
	LOOP
	  FETCH V_CUR INTO V_RN, V_NAME, V_FULLNAME;
		EXIT WHEN V_CUR%NOTFOUND;
    /* добавление строки контрагента */
    ILINE_INDEX := PRSG_EXCEL.LINE_CONTINUE(C_ROW);
		
		PRSG_EXCEL.CELL_VALUE_WRITE(C_PARAM, 0, ILINE_INDEX, q'['']' || V_PNAME || q'[']'); -- PRINT PROC_PARAMS
  
    /* запись значений */
    PRSG_EXCEL.CELL_VALUE_WRITE(C_RN, 0, ILINE_INDEX, V_RN);
    PRSG_EXCEL.CELL_VALUE_WRITE(C_NAME, 0, ILINE_INDEX, V_NAME);
    PRSG_EXCEL.CELL_VALUE_WRITE(C_FULLNAME, 0, ILINE_INDEX, V_FULLNAME);
  
  END LOOP;
	CLOSE V_CUR;

  PRSG_EXCEL.LINE_DELETE(C_ROW);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_EXCEPTION(0, 'NO DATA FOUND');
  WHEN OTHERS THEN
    P_EXCEPTION(0, 'EXCEPTION: '||SQLERRM);
END;


















